# 9569 past-paper topic map: 2020-2024 + specimen (syllabus "For Examination from 2020", pre-Y27 revision)
# Each entry: (question_label, [(topic, subtopics), ...])
YEARS = [
 ("Specimen", "sp",
  [("1", [("Algorithms", "binary search vs linear search, efficiency; insertion sort; bubble sort")]),
   ("2", [("Recursion", "recursive function; trace tree")]),
   ("3", [("Data structures", "BST: draw, array implementation, search, in-order traversal")]),
   ("4", [("Algorithms", "decision tables; pseudocode")]),
   ("5", [("Databases", "ER diagram; 3NF normalisation; table descriptions; foreign keys; NoSQL")]),
   ("6", [("Networks and web", "network threats and protection; securing data transfer")]),
   ("7", [("Ethics", "professional code of conduct")])],
  [("1", [("Number representation", "ASCII; denary/base conversion"), ("Algorithms", "input validation; menus")]),
   ("2", [("Algorithms", "quicksort; second sort algorithm; searching; file handling"), ("Testing", "test evidence")]),
   ("3", [("OOP", "superclass/subclasses; inheritance; polymorphism"), ("Data structures", "linked list; stack; queue")]),
   ("4", [("Databases", "SQL: CREATE, INSERT, SELECT"), ("Web applications", "form input to HTML table")])]),
 ("2020", "2020",
  [("1", [("OOP", "class diagram; superclass; encapsulation; polymorphism")]),
   ("2", [("Algorithms", "quicksort pivot strategies; insertion sort vs quicksort")]),
   ("3", [("Data structures", "BST array implementation; queues: linear vs circular"), ("Recursion", "trace table; stack; tree traversal")]),
   ("4", [("Networks and web", "LAN addressing; protocols; packet switching; DNS; encryption; digital signatures")]),
   ("5", [("Number representation", "validation and verification; modulus-11 check digit")]),
   ("6", [("Databases", "1NF/3NF normalisation; ER diagram; keys; redundancy; SQL query")])],
  [("1", [("Data structures", "hashing: modulus hash function, seeds"), ("Number representation", "ASCII")]),
   ("2", [("Algorithms", "merge sort; random data generation; file handling")]),
   ("3", [("Number representation", "units of data: KB vs KiB (powers of 10 and 2)"), ("Algorithms", "string validation")]),
   ("4", [("Databases", "SQL CREATE"), ("OOP", "classes; inheritance; overriding"), ("Web applications", "list display")])]),
 ("2021", "2021",
  [("1", [("OOP", "class diagram; inheritance"), ("Number representation", "validation techniques")]),
   ("2", [("Databases", "1NF/3NF; ER diagram; keys; update anomaly; SQL query"), ("Ethics", "PDPA obligations")]),
   ("3", [("Networks and web", "denial-of-service; server request handling; firewalls; digital signatures; authentication")]),
   ("4", [("Data structures", "static vs dynamic; memory allocation; queue choice")]),
   ("5", [("Data structures", "hash tables; collisions"), ("Algorithms", "hash vs linear vs binary search")]),
   ("6", [("Number representation", "ASCII; binary; hexadecimal; Unicode")]),
   ("7", [("Data structures", "BST array; insertion"), ("Recursion", "in-order traversal pseudocode")]),
   ("8", [("Recursion", "stack usage; features of recursion; stack overflow")])],
  [("1", [("Number representation", "check digits: IMEI/Luhn algorithm"), ("Testing", "test case design")]),
   ("2", [("Algorithms", "insertion sort; quicksort; time complexity (Big-O)")]),
   ("3", [("Data structures", "linked list; queue"), ("OOP", "subclassing; inheritance")]),
   ("4", [("Databases", "SQL: joins, aggregates"), ("Web applications", "menu and tables")])]),
 ("2022", "2022",
  [("1", [("Databases", "ER diagram; table definitions; keys; SQL query; normalisation"), ("Number representation", "validation technique")]),
   ("2", [("OOP", "class vs object; class diagram; private properties; inheritance")]),
   ("3", [("Networks and web", "encryption; detecting message alteration; authentication")]),
   ("4", [("Data structures", "array vs linked list"), ("Recursion", "linked-list recursion; pseudocode"), ("Algorithms", "merge sort vs quicksort")]),
   ("5", [("Data structures", "dynamic memory allocation; memory leak"), ("Testing", "why faults are missed in testing")]),
   ("6", [("Databases", "data management: backup and archiving")]),
   ("7", [("Networks and web", "packet switching; protocols; routers; firewalls")]),
   ("8", [("Data structures", "hash tables; collisions; hashing algorithm features"), ("Algorithms", "search time complexity")])],
  [("1", [("Number representation", "ASCII; Caesar cipher"), ("Algorithms", "file handling; validation")]),
   ("2", [("Algorithms", "bubble sort; merge sort"), ("Recursion", "recursive binary search")]),
   ("3", [("Data structures", "BST"), ("OOP", "Tree class"), ("Recursion", "recursive insertion; in-order and post-order traversals")]),
   ("4", [("Databases", "SQL: create, insert, join query"), ("Web applications", "table of unreturned loans")])]),
 ("2023", "2023",
  [("1", [("Databases", "3NF; keys; ER diagram"), ("Number representation", "validation and verification"), ("Web applications", "native vs web apps")]),
   ("2", [("Data structures", "static vs dynamic memory; linked-list find pseudocode; stack push pseudocode")]),
   ("3", [("OOP", "inheritance diagram; attributes and methods; private members; polymorphism")]),
   ("4", [("Data structures", "array vs linked list; BST construction and shape; queues: linear vs circular")]),
   ("5", [("Networks and web", "digital signatures; IPv4; packet switching; routers"), ("Number representation", "UTF-8; hexadecimal; binary")]),
   ("6", [("Algorithms", "quicksort; Big-O worst case"), ("Recursion", "definition; iterative-to-recursive rewrite")]),
   ("7", [("Ethics", "PDPA compliance")]),
   ("8", [("Ethics", "professional code of ethics")])],
  [("1", [("Databases", "SQL: create tables, insert, PK/FK")]),
   ("2", [("Data structures", "circular queue"), ("OOP", "classes and methods")]),
   ("3", [("Algorithms", "2D lists; validation logic (Sudoku checker)")]),
   ("4", [("Number representation", "run-length encoding; bit depth"), ("Web applications", "render image grid")])]),
 ("2024", "2024",
  [("1", [("Algorithms", "flowcharts; trace tables; pseudocode"), ("Number representation", "ASCII; hexadecimal; binary")]),
   ("2", [("Recursion", "trace tree; stack; base case; iterative rewrite")]),
   ("3", [("OOP", "class diagram; instantiation; encapsulation, inheritance, polymorphism"), ("Testing", "normal, abnormal, extreme test data")]),
   ("4", [("Databases", "ER diagram; 3NF; table descriptions; SQL CREATE; backup and archiving")]),
   ("5", [("Data structures", "BST array implementation; static structure limits; insertion"), ("Recursion", "reverse in-order traversal")]),
   ("6", [("Networks and web", "client-server; intranet; protocols (SMTP, HTTPS); digital signatures")])],
  [("1", [("Algorithms", "custom multi-key sort; game/scoring logic")]),
   ("2", [("OOP", "Node class"), ("Data structures", "tree stored in a list with pointers"), ("Algorithms", "2^n node pattern; testing")]),
   ("3", [("Web applications", "HTML generation"), ("Algorithms", "string parsing; file handling")]),
   ("4", [("Databases", "SQL: create, insert, availability queries with date expansion")])]),
]

TOPIC_ORDER = ["Algorithms", "Data structures", "Recursion", "OOP", "Number representation",
               "Databases", "Networks and web", "Web applications", "Ethics", "Testing"]
